@WebApplication1_HostAddress = https://localhost:7115

POST {{WebApplication1_HostAddress}}/api/v1/parse-content
Content-Type: application/json

  {
    "type":"INTERNAL_JSON",
    "content":"ew0KIk5hbWUiOiJ0ZXN0MTIzIg0KfQ=="
  }
###
